#!/bin/bash

# Session notes
# Branch: homepage
#
#   Create commentable concern and apply to news articles' and bible lessons' models.

apl=application
con=controller
jscs=javascripts
stss=stylesheets

ecss=.css.erb
ehtm=.html.erb
ejvs=.js.erb

a=app
  as=$a/assets
    jss=$as/$jscs
    css=$as/$stss
  cts=$a/${con}s
  mds=$a/models
  vs=$a/views
    lyv=$vs/layouts
    apv=$vs/$apl
    usv=$vs/users
cf=config
  izs=$cf/initializers
db=db
  sma=$db/schema.rb
  mgs=$db/migrate

if [ $# -gt 0 ]
then
  for c
  do
    case $c in
      -n) # nautilus
        nautilus . &
        ;;
      -s) # session
        gedit --new-window session &
        ;;
      -r) # routes
        gedit --new-window $cf/routes.rb $sma &
        ;;
      -a) # application
        gedit --new-window $izs/assets.rb $css/$apl.scss $css/goyim$ecss $lyv/$apl$ehtm $apv/*$ehtm &
        ;;
      -u) # users
        gedit --new-window $lyv/users$ehtm $css/users.scss $usv/login$ehtm $usv/dashboard$ehtm $usv/index$ehtm &
        ;;
      -c) # controllers
        gedit --new-window $cts/*_$con.rb &
        ;;
      -m) # models
        gedit --new-window $mds/*.rb &
        ;;
      -g) # migrations
        gedit --new-window $mgs/*.rb &
        ;;
      *)
        ;;
    esac
  done
else
  session -n -s -r -a -u -c -m -g
fi
