# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00d506250b820e7273c4aaaac7f506adc088c99ea19f58c0ebef2758c0cd37e7533d01204768a80909251af68c2154238eebe04f5e1c181ba0f003f21877fc07

test:
  secret_key_base: 9de515b77ec7758103dcb0842d308f404dca61f9ed75d7df623b69cbc1f8cebd686173603948343decc7615d9deeaa4500b48b206407c80f894074e8c18b5c5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
